import time
print("menghitung luas segitiga by niko")
time.sleep(1)
print("loading....")
time.sleep(2)
a = input("nama anda:")
b = input("umur:")
c = input("gak takut ketahuan guru?:")
print("loading...")
time.sleep(2)
d = input("alas:")
e = input("tinggi:") 
f = float(d) * float(e) / 2
print("jadi luas nya adalah:", f)
time.sleep(1)
print("jangan lupa subscribe canel NIKO WNC")
time.sleep(1)
g = input("anda butuh bantuan lain?:")
print("loading....")
time.sleep(2)
print("baiklah jika anda tidak butuh bantuan")
time.sleep(1)
print("sampai jumpa lagi🐰")
time.sleep(1)
print("ee sebentar")
h = input ("untuk keluar ketik exit:")
print("loading....")
time.sleep(2)
print("kena tipu awokawok keluar sendiri sana")
time.sleep(1)
print("jan baper ya om")